### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by alexmarmute** [myrmex-org/myrmex#55]
Using "lager deploy-roles PlanetExpressLambdaExecution -e DEV -s v0" i received this stack trace because i didn`t configure my aws credentials:

```
Unhandled rejection InvalidClientTokenId: The security token included in the request is invalid.
    at Request.extractError (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:673:12)
    at Request.callListeners (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/request.js:673:12)
    at Request.callListeners (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/alexsouza/Projects/LagerJs-Lambda/planet-express/node_modules/aws-sdk/lib/event_listeners.js:230:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

I wish it would have a more user-friendly message.

**Comment by AlexisNo** [comment]
The message "The security token included in the request is invalid" is from the AWS SDK and explicit
