### ISSUE TITLE
"No available IAM Role" warn missing when creating Lambda

### ISSUE THREAD

**Issue by radAragon** [myrmex-org/myrmex#83]
Hi. I was creating a fresh Myrmex project then received the following error when creating a Lambda without IAM Roles (yet):

> $ myrmex create-lambda example
> ? Choose the runtime nodejs6.10
> ? Choose the timeout (in seconds) 30
> ? Choose the memory  256 MB
> ? Where can we find the execution role of the Lambda? Select a role managed by the plugin @myrmex/iam
> ? Choose the execution role 
> 
> [2017-10-19T17:09:43.126Z] FATAL: Uncaught Exception: Cannot read property 'value' of undefined
> TypeError: Cannot read property 'value' of undefined
> ...
> ...
>     at emitOne (events.js:96:13)
>     at Interface.emit (events.js:188:7)
> 
> More information in myrmex.log

As you can see in the log there was no option in the "Choose the execution role" question to accept that I still had no IAM Roles and instead I received that error at pressing Enter.

I think I should receive a warning before entering this dead end question or just don't show this option (managed role) if there's no IAM Role.

Thanks in advance.

**Comment by AlexisNo** [comment]
The prompt `Where can we find the execution role of the Lambda? ` as three possible answers as you can see [here](https://github.com/myrmex-org/myrmex/blob/master/packages/lambda/src/cli/create-lambda.js#L138-L152) :
* Select a role managed by the plugin @myrmex/iam
* Select a role in your AWS account
* Enter the value manually

If you don't want to be blocked and prefer to enter the value later, you can select the 3rd option and enter a fake value for [the question](https://github.com/myrmex-org/myrmex/blob/master/packages/lambda/src/cli/create-lambda.js#L99) `Enter the IAM role that will be used to execute the Lambda function`.

Nevertheless, the option `Select a role managed by the plugin @myrmex/iam` should be hidden if there is no role defined in the plugin.

I admit I do not work a lot on Myrmex these days because I do not have a laptop at home. But be sure that I will work on it if a blocking bug is reported.
